# Generated by Django 4.2.3 on 2023-07-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_remove_url_link'),
    ]

    operations = [
    ]
